### ISSUE TITLE
methods of `OpenBD::Resources::Onix` and `OpenBD::Resources::Hanmoto`

### ISSUE THREAD

**Issue by takahashim** [nasum/openbd_api#11]
ところで`OpenBD::Resources::Summary`のメソッドは今の実装で問題ないかと思いますが、`OpenBD::Resources::Onix`と`OpenBD::Resources::Hanmoto` のメソッドってどういう風にするか（したいか）何か構想はありますか？

**Comment by nasum** [comment]
そうですね。`OpenBD::Resources::Summary` のように各項目をメソッドで取れるようにするのが親切かなと思うのですが、結構ネストしていてどうしようかなと悩んでいるところです。
とりあえずまずは一番浅い層から取れるようにするのがいいかなと思ってます。`onix`だとしたら`PublishingDetail` の層までメソッドにする感じですね。

**Comment by takahashim** [comment]
なるほど、とはいえ深いのは使う側にはめんどくさいのでメソッド一発で値を拾いたいのですよね…

**Comment by nasum** [comment]
ですよね。ある程度必要そうなものを抜擢してメソッド一発で取れるようにして、細かいのが欲しい人は`source` を見てもらうとかがいいかもしれないです。

**Comment by takahashim** [comment]
こちら両方ともマージしていただいてありがとうございました！
というわけでこちらのissueは閉じます。
