### ISSUE TITLE
`source` ambiguity

### ISSUE THREAD

**Issue by takahashim** [nasum/openbd_api#13]
openBDのJSONで、hanmotoの属性にreviewsがあり、さらにその属性にsourceというのがあります。
このため`OpenBD::Resources::BaseResource`を継承して`OpenBD::Resources::Hanmoto::Review`みたいなクラスを作ろうとするとちょっとまずい感じなのでした…。

どうするのがいいでしょうか。

**Comment by nasum** [comment]
@takahashim すみません。反応できないでいました :sweat_drops: 
そうですね、これは想定外でした・・・。ちょっとすぐ答えを出せないのでどうすればいいか考えてみます。

**Comment by takahashim** [comment]
いえいえ。お暇な時にでも対応していただければ。

とりあえずこのJSONでは省略名は少なさそうなので、  `BaseResource#source` を `BaseResource#src` にする辺りが無難でしょうか…。

**Comment by nasum** [comment]
srcにするのが良さそうですね。ぱっと見わかるとも思います。
